# Generated by Django 4.2.9 on 2025-09-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
