# Generated by Django 4.2.9 on 2025-09-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0002_volunteerprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
