# Generated by Django 4.2.9 on 2026-01-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0005_alter_contact_created_at_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for blog post', null=True, upload_to='blog_images/'),
        ),
    ]
