# Generated by Django 4.2.9 on 2026-04-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0006_newsletter_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text='Brief description shown on the blog page', max_length=300)),
                ('content', models.TextField(help_text='Write naturally - no HTML needed')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('published', models.BooleanField(default=False, help_text='Check to make visible on blog page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
