# Generated by Django 4.2.9 on 2026-04-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0007_blogpost_alter_newsletter_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRenovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the beneficiary', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the renovation')),
                ('before_image', models.ImageField(upload_to='renovations/')),
                ('after_image', models.ImageField(upload_to='renovations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
