# Generated by Django 4.2.9 on 2026-04-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0008_houserenovation'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='address',
            field=models.CharField(choices=[('addis_ababa', 'Addis Ababa'), ('bishoftu', 'Bishoftu'), ('adama', 'Adama'), ('debre_zeit', 'Debre Zeit'), ('mojo', 'Mojo'), ('dukem', 'Dukem')], default='addis_ababa', max_length=50),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
