# Generated by Django 4.2.9 on 2026-04-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0009_volunteerprofile_address_volunteerprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person (e.g., Aboye Waqjira)', max_length=200)),
                ('title', models.CharField(help_text='Story title (e.g., A Journey from Streets to Dignity)', max_length=300)),
                ('tag', models.CharField(help_text='Story tag (e.g., Miraculous Recovery)', max_length=100)),
                ('date_info', models.CharField(help_text='Date information (e.g., Joined May 27, 2018)', max_length=100)),
                ('location_info', models.CharField(help_text='Location information (e.g., ROTOM Center)', max_length=100)),
                ('content', models.TextField(help_text='Full story content - use paragraphs separated by blank lines')),
                ('image_1', models.ImageField(help_text='First image (Before)', upload_to='stories/')),
                ('image_1_label', models.CharField(default='Before', max_length=50)),
                ('image_2', models.ImageField(help_text='Second image (After)', upload_to='stories/')),
                ('image_2_label', models.CharField(default='After', max_length=50)),
                ('image_3', models.ImageField(help_text='Third image', upload_to='stories/')),
                ('image_3_label', models.CharField(default='At Center', max_length=50)),
                ('stat_1_number', models.CharField(help_text='First statistic number (e.g., 6)', max_length=20)),
                ('stat_1_text', models.CharField(help_text='First statistic text (e.g., Weeks to Walk)', max_length=50)),
                ('stat_2_number', models.CharField(help_text='Second statistic number', max_length=20)),
                ('stat_2_text', models.CharField(help_text='Second statistic text', max_length=50)),
                ('stat_3_number', models.CharField(help_text='Third statistic number', max_length=20)),
                ('stat_3_text', models.CharField(help_text='Third statistic text', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('layout', models.CharField(choices=[('normal', 'Images Left'), ('reverse', 'Images Right')], default='normal', max_length=20)),
                ('published', models.BooleanField(default=True, help_text='Check to display on stories page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
