# Generated by Django 5.2.3 on 2026-04-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0010_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Package title (e.g., Home Care Support)', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in ETB', max_digits=10)),
                ('description', models.CharField(help_text='Short description (e.g., Supports a senior living at home for one month)', max_length=300)),
                ('features', models.TextField(help_text='List of features, one per line')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Check to display on donation page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Donation Packages',
                'ordering': ['order', 'amount'],
            },
        ),
    ]
