# Generated by Django 5.2.3 on 2026-04-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0011_donationpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Student's name (e.g., Meron Tadesse)", max_length=200)),
                ('role', models.CharField(help_text='Role/Status (e.g., University Student, Age 19)', max_length=200)),
                ('quote', models.TextField(help_text='Their testimonial/story')),
                ('image', models.ImageField(help_text='Main photo', upload_to='champions/')),
                ('years_supported', models.CharField(help_text='e.g., 5 or 3-5', max_length=50)),
                ('achievement', models.CharField(help_text='e.g., 1st In Family to University or Top 5% Class Ranking', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('layout', models.CharField(choices=[('normal', 'Image Left'), ('reverse', 'Image Right')], default='normal', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Check to display on champions page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Champions',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
