# Generated by Django 5.2.3 on 2026-04-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0013_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='Year of the milestone (e.g., 2017)', max_length=10)),
                ('title', models.CharField(help_text='Milestone title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the milestone')),
                ('image', models.ImageField(help_text='Milestone photo', upload_to='milestones/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', help_text='Position on timeline (alternates left/right)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Check to display on timeline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Milestones',
                'ordering': ['order', 'year'],
            },
        ),
    ]
