# Generated by Django 5.2.3 on 2026-04-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0015_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Photo title (e.g., Dining Room)', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the space')),
                ('image', models.ImageField(help_text='Center photo', upload_to='center/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Check to display in gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Center Photos',
                'ordering': ['order', 'title'],
            },
        ),
    ]
