# Generated by Django 5.2.3 on 2026-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0016_centerphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pattern name (e.g., Green Ethiopian Pattern)', max_length=200)),
                ('image', models.ImageField(help_text='Pattern image (recommended: horizontal repeating pattern)', upload_to='patterns/')),
                ('height', models.IntegerField(default=60, help_text='Pattern bar height in pixels (default: 60)')),
                ('opacity', models.DecimalField(decimal_places=2, default=0.8, help_text='Pattern opacity (0.00 to 1.00, default: 0.80)', max_digits=3)),
                ('is_active', models.BooleanField(default=False, help_text='Check to use this pattern on the navbar (only one can be active)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Navbar Patterns',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
