# Generated by Django 5.2.3 on 2026-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0017_navbarpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Partner organization name', max_length=200)),
                ('logo', models.ImageField(help_text='Partner logo (recommended: transparent PNG, square or landscape)', upload_to='partners/')),
                ('website', models.URLField(blank=True, help_text='Partner website URL (optional)')),
                ('description', models.TextField(blank=True, help_text='Brief description of the partnership (optional)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Check to display in partners section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Partners',
                'ordering': ['order', 'name'],
            },
        ),
    ]
