# Generated by Django 5.2.3 on 2026-05-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0019_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
    ]
