# Generated by Django 5.2.3 on 2026-05-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0020_remove_testimonial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='story_poster',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
    ]
