# Generated by Django 5.2.3 on 2026-05-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0020_remove_testimonial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_am',
            field=models.TextField(blank=True, help_text='Amharic translation of content (optional)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='summary_am',
            field=models.CharField(blank=True, help_text='Amharic translation of summary (optional)', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_am',
            field=models.CharField(blank=True, help_text='Amharic translation of title (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='centerphoto',
            name='description_am',
            field=models.TextField(blank=True, help_text='Amharic translation of description (optional)'),
        ),
        migrations.AddField(
            model_name='centerphoto',
            name='title_am',
            field=models.CharField(blank=True, help_text='Amharic translation of title (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='champion',
            name='achievement_am',
            field=models.CharField(blank=True, help_text='Amharic translation of achievement (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='champion',
            name='quote_am',
            field=models.TextField(blank=True, help_text='Amharic translation of quote (optional)'),
        ),
        migrations.AddField(
            model_name='champion',
            name='role_am',
            field=models.CharField(blank=True, help_text='Amharic translation of role (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='donationpackage',
            name='description_am',
            field=models.CharField(blank=True, help_text='Amharic translation of description (optional)', max_length=300),
        ),
        migrations.AddField(
            model_name='donationpackage',
            name='features_am',
            field=models.TextField(blank=True, help_text='Amharic translation of features, one per line (optional)'),
        ),
        migrations.AddField(
            model_name='donationpackage',
            name='title_am',
            field=models.CharField(blank=True, help_text='Amharic translation of title (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='description_am',
            field=models.TextField(blank=True, help_text='Amharic translation of description (optional)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_am',
            field=models.CharField(blank=True, help_text='Amharic translation of title (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption_am',
            field=models.TextField(blank=True, help_text='Amharic translation of caption (optional)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title_am',
            field=models.CharField(blank=True, help_text='Amharic translation of title (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='houserenovation',
            name='description_am',
            field=models.TextField(blank=True, help_text='Amharic translation of description (optional)'),
        ),
        migrations.AddField(
            model_name='houserenovation',
            name='name_am',
            field=models.CharField(blank=True, help_text='Amharic translation of name (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='milestone',
            name='description_am',
            field=models.TextField(blank=True, help_text='Amharic translation of description (optional)'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='title_am',
            field=models.CharField(blank=True, help_text='Amharic translation of title (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_am',
            field=models.TextField(blank=True, help_text='Amharic translation of description (optional)'),
        ),
        migrations.AddField(
            model_name='previousevent',
            name='description_am',
            field=models.TextField(blank=True, help_text='Amharic translation of description (optional)'),
        ),
        migrations.AddField(
            model_name='previousevent',
            name='title_am',
            field=models.CharField(blank=True, help_text='Amharic translation of title (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='story',
            name='content_am',
            field=models.TextField(blank=True, help_text='Amharic translation of content (optional)'),
        ),
        migrations.AddField(
            model_name='story',
            name='date_info_am',
            field=models.CharField(blank=True, help_text='Amharic translation of date info (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='image_1_label_am',
            field=models.CharField(blank=True, help_text='Amharic label (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='image_2_label_am',
            field=models.CharField(blank=True, help_text='Amharic label (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='image_3_label_am',
            field=models.CharField(blank=True, help_text='Amharic label (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='location_info_am',
            field=models.CharField(blank=True, help_text='Amharic translation of location info (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='stat_1_text_am',
            field=models.CharField(blank=True, help_text='Amharic translation (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='stat_2_text_am',
            field=models.CharField(blank=True, help_text='Amharic translation (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='stat_3_text_am',
            field=models.CharField(blank=True, help_text='Amharic translation (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='tag_am',
            field=models.CharField(blank=True, help_text='Amharic translation of tag (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='title_am',
            field=models.CharField(blank=True, help_text='Amharic translation of title (optional)', max_length=300),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_am',
            field=models.CharField(blank=True, help_text='Amharic translation of position (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_am',
            field=models.TextField(blank=True, help_text='Amharic translation of quote (optional)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_am',
            field=models.CharField(blank=True, help_text='Amharic translation of role (optional)', max_length=200),
        ),
    ]
