# Generated by Django 5.2.3 on 2026-05-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0021_add_amharic_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('navbar', 'Navbar'), ('home', 'Home Page'), ('about', 'About Us Page'), ('centerbased', 'Center-Based Care Page'), ('homebased', 'Home-Based Care Page'), ('champions', 'Champions / Grandchildren Page'), ('stories', 'Stories Page'), ('takeaction', 'Take Action Page'), ('volunteer', 'Volunteer Page')], db_index=True, max_length=50)),
                ('key', models.CharField(db_index=True, help_text='Internal identifier (e.g. hero_title, hero_subtitle)', max_length=100)),
                ('label', models.CharField(help_text='Human-readable label shown in the dashboard', max_length=200)),
                ('value', models.TextField(help_text='The text content displayed on the website')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
                'ordering': ['page', 'key'],
                'unique_together': {('page', 'key')},
            },
        ),
    ]
