# Generated by Django 5.2.3 on 2026-05-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0021_event_story_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title or description', max_length=200)),
                ('image', models.ImageField(help_text='Volunteer activity photo', upload_to='volunteer_gallery/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Check to display in gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Volunteer Gallery',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
