# Generated by Django 5.2.3 on 2026-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0022_add_site_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='value_am',
            field=models.TextField(blank=True, default='', help_text='Amharic translation (optional)'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='value',
            field=models.TextField(blank=True, help_text='The text content displayed on the website (English)'),
        ),
    ]
