# Generated by Django 4.2.9 on 2026-05-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0024_merge_server_and_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='quote',
            field=models.TextField(default='', help_text="Featured quote from the story (e.g., 'I never thought I would walk again.')"),
        ),
        migrations.AddField(
            model_name='story',
            name='quote_am',
            field=models.TextField(blank=True, help_text='Amharic translation of quote (optional)'),
        ),
    ]
