# Generated by Django 4.2.9 on 2026-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0026_story_name_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='name_am',
            field=models.CharField(blank=True, help_text='Amharic translation of name (optional)', max_length=200),
        ),
    ]
