# Generated by Django 4.2.9 on 2026-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotom', '0028_teammember_name_am'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.TextField(blank=True, help_text='Image caption/description (optional)'),
        ),
    ]
