"""
Django settings for REACHONEETH project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config  # Move import to top for better practice

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = os.path.join(BASE_DIR, 'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable for production
SECRET_KEY = config('SECRET_KEY', default='django-insecure-na2_qyrfj%e%yru916ayxro1=4t1#6h@p1)qp4f)-)#2v9b8zd')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)  # Set to False on PythonAnywhere

# For PythonAnywhere, add your domain here (replace 'yourusername' with actual)
ALLOWED_HOSTS = ['rotom.pythonanywhere.com', '127.0.0.1']  # Add '*' for dev, but not prod

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',  # Uncomment if you need admin in production
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rotom',
    'dashboard',
    'paypal.standard.ipn'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'REACHONEETH.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'REACHONEETH.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# For PythonAnywhere free tier, SQLite is fine for low-traffic; switch to MySQL for better prod
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# For MySQL on PythonAnywhere (uncomment and configure if preferred):
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'yourusername$yourdbname',  # Create in PA Dashboard > Database
#         'USER': 'yourusername',
#         'PASSWORD': config('DB_PASSWORD'),  # Set as env var
#         'HOST': 'yourusername.mysql.pythonanywhere-services.com',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# PayPal Settings
PAYPAL_RECEIVER_EMAIL = 'rotomethiopia@reachone-touchone.org'
PAYPAL_TEST = config('PAYPAL_TEST', default=True, cast=bool)  # Set to False for live

LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_URL = '/dashboard/login/'
LOGOUT_REDIRECT_URL = '/dashboard/login/'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
# For PythonAnywhere: Set STATIC_ROOT to absolute path in your project dir
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Collect here, then map in PA Web tab
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Chapa (Ethiopian payment gateway) - already using config, good
CHAPA_SECRET_KEY = config('CHAPA_SECRET_KEY', default='CHASECK-O6jk9SKQlZJcn8d9qib00WLbvzcRJreo')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Additional production settings for security
if not DEBUG:
    # Enforce HTTPS in production
    SECURE_SSL_REDIRECT = True
    # Security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # Sessions
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS (optional, but recommended)
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True